name: Deploy React App to NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to NAS
        env:
          NAS_HOST: ${{ secrets.NAS_HOST }}
          NAS_USER: ${{ secrets.NAS_USER }}
          NAS_DEPLOY_PATH: ${{ secrets.NAS_DEPLOY_PATH }}
          SSH_KEY: ${{ secrets.NAS_SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > deploy_key
          chmod 600 deploy_key
          cat deploy_key
          ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.NAS_USER }}@${{ secrets.NAS_HOST }} "echo Connected"
          chmod +x deploy.sh
          ./deploy.sh $NAS_HOST $NAS_USER $NAS_DEPLOY_PATH deploy_key
          rm deploy_key
